print("--Student Details--")
usn=input("Enter student USN:")
name=input("Enter student Name:")
crs=input("Enter your course:")
sem=input("Enter you cureent sem:")
clg=input("Enter your university name:")
print("--Your Details--")
print("USN:",usn)
print("Name:",name)
print("Course:",crs)
print("Semester:",sem)
print("Your university:",clg)